# This is a basic workflow to help you get started with Actions

name: Upload Logs to S3

on:
  workflow_run:
    workflows: ["Terraform Plan & Apply"]
    types:
      - completed
      - failed

jobs:
  upload-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Download logs
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./logs

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: buckettest2875
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: ./logs
          DEST_DIR: actionlogs/
